### ISSUE TITLE
O módulo Pagar.me quebra outros módulos de meios de pagamento.

### ISSUE THREAD

**Issue by ricardotulio** [pagarme/pagarme-magento#154]
## Contexto

O módulo atual quebra outros meios de pagamento que possam estar instalados na plataforma.

## Ambiente

* Magento Community 1.8.1.0
* Módulo Pagar.me v2
* Servidor Linux
* PHP 5.4
* Apache 2.2
* MySQL 5.6

## Passos para reproduzir

1. Instale o módulo Pagar.me
2. Faça uma compra utilizando outro meio de pagamento

## Resultado esperado

A compra deveria ser feita com sucesso.

## Resultado atual

É exibido um alert com a mensagem `Unable to set Payment Method`.

## Posssível correção

É lançado a seguinte exceção: 

```php
#0 /var/www/vendor/pagarme/pagarme-php/lib/Transaction/TransactionHandler.php(110): PagarMe\Sdk\Transaction\TransactionHandler->buildTransaction(Array)
#1 /var/www/app/code/community/PagarMe/Checkout/Model/Total.php(43): PagarMe\Sdk\Transaction\TransactionHandler->get(NULL)
#2 /var/www/app/code/core/Mage/Sales/Model/Quote/Address.php(1013): PagarMe_Checkout_Model_Total->collect(Object(Mage_Sales_Model_Quote_Address))
#3 /var/www/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#4 /var/www/app/code/core/Mage/Sales/Model/Quote/Payment.php(148): Mage_Sales_Model_Quote->collectTotals()
#5 /var/www/app/code/core/Mage/Checkout/Model/Type/Onepage.php(631): Mage_Sales_Model_Quote_Payment->importData(Array)
#6 /var/www/app/code/core/Mage/Checkout/controllers/OnepageController.php(475): Mage_Checkout_Model_Type_Onepage->savePayment(Array)
#7 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->savePaymentAction()
#8 /var/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('savePayment')
#9 /var/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/index.php(87): Mage::run('', 'store')
#13 {main}
```

Acredito que deve haver alguma forma de verificar se a ordem está sendo feita por outro meio de pagamento e não passar pela lógica contida no objeto `PagarMe_Checkout_Model_Total`.

## Screenshots

<a href="https://ibb.co/bEkUFa"><img src="https://preview.ibb.co/hdqwva/screenshot_erro.png" alt="screenshot erro" border="0" /></a>

**Comment by henriquekano** [comment]
Não ocorre mais.
